name: Backend CI

on:
  push:
    branches: ["dev", "stage", "main"]
  pull_request:
    branches: ["dev", "stage", "main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install deps
        run: npm install --legacy-peer-deps
        working-directory: ./server

      - name: Run Linter
        run: npm run lint
        working-directory: ./server

      - name: Run Tests
        run: npm test -- --watchAll=false
        working-directory: ./server

      - name: Build
        run: npm run build
        working-directory: ./server

      - name: Upload Dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-dist
          path: ./server/dist
